#==============================================================================
# RISCV64 Processor
# Generic Xcelium Makefile
#==============================================================================

TOP ?= tb_pc

XRUN_DIR  = ../xrun
LOG_DIR   = ../logs
WAVE_DIR  = ../waves

RTL_FLIST = Flist.rtl
TB_FLIST  = Flist.tb

XRUN = xrun

XRUN_FLAGS =                 \
	-64bit                   \
	-sv                      \
	-access +rwc             \
	-linedebug               \
	-clean                   \
	-xmlibdirname $(XRUN_DIR)/$(TOP)

.PHONY: clean build run wave

build:
	mkdir -p $(XRUN_DIR)
	mkdir -p $(LOG_DIR)
	mkdir -p $(WAVE_DIR)

	$(XRUN) $(XRUN_FLAGS) \
		-F $(RTL_FLIST) \
		-F $(TB_FLIST) \
		-top $(TOP) \
		-input waves.tcl \
		-log $(LOG_DIR)/$(TOP).log

run:
	@echo "Simulation already executed during build."

wave:
	simvision $(WAVE_DIR)/waves.shm &

clean:
	rm -rf $(XRUN_DIR)
	rm -rf $(LOG_DIR)
	rm -rf $(WAVE_DIR)
	rm -rf xcelium.d
	rm -rf INCA_libs
	rm -f *.history
	rm -f *.key
	rm -f *.log
